### ISSUE TITLE
Batterymonitor is not working on a S10X21

### ISSUE THREAD

**Issue by RobertHerter** [jnk-cons/e3dc-4-homey#21]
No Values are shown/Transmittet on an S10X21, every other devices working.

Send you an Report: 8a834ae1-506f-4b3d-acbc-7366cefb80c0

**Comment by jnk-cons** [comment]
@RobertHerter  Thank you for the submit. Can you go into the settings of the Hauskraftwerk device and activate and save the debug mode? Then please wait 1 min and send a diagnostic report again? Thank you

**Comment by RobertHerter** [comment]
Done.

New Report: 888f3f79-a33d-4f2b-b9de-6551eeebaf88

**Comment by jnk-cons** [comment]
@RobertHerter Fixed in 1.0.3 (should be installed soon)

**Comment by RobertHerter** [comment]
Installed and Working Thank you.
